name: Node.js CI

on:
  push:
    branches:
      - main
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup npm package
        run: npm install
      - name: Build website
        run: npm build
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
  # jest:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Jest unit testing
  #       uses: actions/checkout@v2
  #     - name: Install modules
  #       run: npm install
  #     - name: Run Jest
  #       run: npm run jest

  heroku:
    runs-on: ubuntu-latest
    needs: [cypress-run]
    steps:
    - uses: actions/checkout@v2
    - uses: akhileshns/heroku-deploy@v3.8.9 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
        heroku_email: ${{secrets.HEROKU_EMAIL}}